### ISSUE TITLE
Unsupported version of OpenAPI document

### ISSUE THREAD

**Issue by starwarskidfan** [node-red/node-red-nodegen#103]
I am getting an error for unsupported version of OpenAPI document.

I am not able to find documentation on what versions it supports. Can someone point me into the right direction?

**Comment by dceejay** [comment]
It supports Swagger v2

**Comment by kazuhitoyokoi** [comment]
If you want to use Swagger v3, the following procedures will be useful.
https://github.com/node-red/node-red-nodegen/blob/0.1.0/docs/index.md#openapi-specification-30

**Comment by kazuhitoyokoi** [comment]
I will close it because the reaction icon looks solved. :)
