### ISSUE TITLE
Failed conversion of 3.0.1 OpenAPI spec to Swagger 2

### ISSUE THREAD

**Issue by RNCTX** [node-red/node-red-nodegen#108]
### What are the steps to reproduce?

1. Download OpenAPI 3.0.1 reference for Kroger API at https://developer.kroger.com/reference
2. Convert to Swagger 2 via instructions in [this post](https://github.com/node-red/node-red-nodegen/issues/105) describing a similar issue.
3. generate node with nodegen

### What happens?

I get a *mostly* working node, but it seems to be missing the parts of the spec dealing with access token variables. Instead of those I just get a "name" box that auto-sets to a node id when clicked.

![image](https://user-images.githubusercontent.com/13775820/79625349-3d76f780-80ee-11ea-8dc4-3c3fb30a294a.png)

![image](https://user-images.githubusercontent.com/13775820/79625356-5da6b680-80ee-11ea-8554-69aee86b3ee1.png)

### What do you expect to happen?

A node that can have variables defined for oauth tokens.

### Please tell us about your environment:

- [ ] Node generator version: 0.1.0
- [ ] Node-RED version: 1.0.5
- [ ] Node.js version: 12.13.0
- [ ] npm version: 6.14.4
- [ ] Platform/OS: Ubuntu 18.04
- [ ] Browser: Chrome

**Comment by kazuhitoyokoi** [comment]
@RNCTX Thank you for the information. Kroger API uses OAuth 2.0 but the current implementation of the Node generator doesn't support OAuth 2.0. That is the reason why the configuration node has no input UI for OAuth 2.0.
