### ISSUE TITLE
Handling Swagger files with large number of APIs

### ISSUE THREAD

**Issue by jdesai61** [node-red/node-red-nodegen#112]
### What are the steps to reproduce?
Use Node generator on any swagger json file with a large number of APIs (e.g. > 1000). For example: https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json

### What happens?
The Node generator is able to generate code without any issues. But once you import the generated node in node-red, the browser based admin UI is extremely unresponsive when trying to use the generated node. For example, when I drag such a node in a flow and double click on it, my browser takes a few minutes to bring up the Edit node window.

### What do you expect to happen?
I understand that the part of the solution is with node-red admin ui and/or browser(s). However, I was wondering is it possible for Node generator to provide a sub-grouping mechanism so it can generate smaller nodes instead of one large one.

### Please tell us about your environment:

- [ ] Node generator version: 0.1.0
- [ ] Node-RED version: v1.0.6
- [ ] Node.js version: v14.4.0
- [ ] npm version: 6.14.5
- [ ] Platform/OS: Tried on Ubuntu and Windows 10
- [ ] Browser: Chrome (worse), Firefox (slightly better)

**Comment by kazuhitoyokoi** [comment]
I encountered the same situation when I used k8s API. Because of a large HTML file, my Node-RED flow editor froze. Unfortunately, there is no sub-grouping mechanism that you mentioned. Therefore, I recommend that the large Swagger file is split into multiple files manually before generating nodes. And then, we can create a single module that contains the generated nodes.

**Comment by jdesai61** [comment]
Thanks - can I create single module using nodegen or do I have to do it manually?
Thanks,
Jatin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kazuhitoyokoi** [comment]
As of now, you need to do it manually. 🙏

**Comment by jdesai61** [comment]
Thank you. I am closing the issue.
