### ISSUE TITLE
(0.20) env.get added to Function node 

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-nodegen#87]
In Node-RED 0.20, we're adding a new function to the Function node that provides access to environment variables:

    let foo = env.get('MY_ENV_VAR');
 
This will also be used at a later date to access Subflow Instance properties and Project Settings - but for now only accesses env vars.

The commit adding this to the `dev` branch is here: https://github.com/node-red/node-red/commit/0c5a76b39145a1b00d97359311723fe0465f6c6c

Nodegen will need to be updated to support this. I believe it could be added today - it is backward compatible.

Design note on using env vars - https://github.com/node-red/node-red/wiki/Design:-Using-environment-variables

**Comment by kazuhitoyokoi** [comment]
@knolleary Thank you for the detail information. Once @HiroyasuNishiyama merged pull request, #86, I'm going to implement the function. I also added it into [our roadmap](https://github.com/node-red/node-red-nodegen/projects/1).

**Comment by kazuhitoyokoi** [comment]
@knolleary I updated the function node template in the commit, https://github.com/node-red/node-red-nodegen/commit/17d29820c140155dd2e5a3c144e4362683a9a096. Sorry for the late response.
