### ISSUE TITLE
Ubable to get this working using the function node method

### ISSUE THREAD

**Issue by ngservices** [node-red/node-red-nodegen#92]
### What are the steps to reproduce?
Follow the Example 2 instructions

### What happens?
It produces an error on step 2 in the console

### What do you expect to happen?
I don't know 
### Please tell us about your environment:

- [x] Node generator version: Latest
- [x] Node-RED version: Latest
- [x] node.js version: Latest
- [x] npm version: Latest
- [x] Platform/OS: Windows 7
- [x] Browser: Chrome 

I'm still learning how to navigate and work with command line so i apologize if this is a dumb question.
I had followed your example 2, exported a function node from node red to a directory.
I then tried node-red-nodegen ~/.node-red/lib/function/lower-case.js

I get an error  Error:ENOENT: no such file or directory, open C:\Users\daniel.smith/.node-red/lib/function/lower-case.js\.node-red\lib\function.

I haven't been able to get any further.

Hope you can help.

Kind regards

**Comment by kazuhitoyokoi** [comment]
Thank you for using Node generator.
Because the example is for Unix environments like macOS and Linux, the file separator is "/".
On Windows OS, the file separator is "\\". Therefore, you need to replace the separators.
Could you try the following command?

> node-red-nodegen C:\\Users\\daniel.smith\\.node-red\\lib\\function\\lower-case.js

**Comment by ngservices** [comment]
Hello mate.
Apologies for delay, i have been on leave for a week. 
I tired the command you advised and it still did not work. 

I tried this 
node-red-nodegen ~\.node-red\lib\function\lower-case.js

This resulted in the same error

I then tried 
node-red-nodegen C:\Users\daniel.smith\.node-red\lib\function\lower-case.js

Result was, 
Error: Type error cannot read property 'match' of undefined

Any suggestions ?

Thanks you

**Comment by ngservices** [comment]
Hello Sir.

I have attached the "lower-case.js" for your viewing. You said you think there is problem with code.

is this something that has been fixed ?

Thank you.

 

Dan 

[functions.zip](https://github.com/node-red/node-red-nodegen/files/2489989/functions.zip)

**Comment by ngservices** [comment]
Hello 
I was exporting wrong, yes. I was exporting the whole function node to library.

So i copied the exact way you have shown and it still has the same error.

Here is the full path i used. 
node-red-nodegen C:\Users\daniel.smith.node-red\lib\functions\lower-case.js

Here is the path to lower-case.js using 

![lower case issues](https://user-images.githubusercontent.com/28897425/47130809-f11ae380-d2cd-11e8-9b88-4614e8ea8480.jpg)

![lower case issues 2](https://user-images.githubusercontent.com/28897425/47130853-1d366480-d2ce-11e8-8058-b950edbad138.jpg)

**Comment by ngservices** [comment]
My apologies.

It has worked, Ill follow the rest of the tutorial to see if i can get it back into node red as a custom module.

Kind regards

**Comment by ngservices** [comment]
Next issue is.
When it completes the creation of the module, i cannot find the actual package on the system.
I followed your tutorial again. 
Sorry for the tedious step by step !


![lower case issues 2](https://user-images.githubusercontent.com/28897425/47131589-1c073680-d2d2-11e8-982c-cf12a4bc801a.jpg)

**Comment by ngservices** [comment]
Its working like a charm my friend.
Love it.

Finally will be able to make simple modules .

Kind regards

**Comment by kazuhitoyokoi** [comment]
@ngservices Good! I'll close this issue.
